using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Quoter.Web.Data.Entities
{
	/// <summary>
	/// This represents a quoter application that has registered
	/// </summary>
	public class AppRegistration
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public Guid Id { get; set; }

		/// <summary>
		/// An identifier generated by the application on instalation.
		/// </summary>
		public string Identifier { get; set; }

		/// <summary>
		/// Ip address (if available) where the application was installed
		/// </summary>
		public string? IpAddress { get; set; }

		public DateTime RegisteredDateTime { get; set; }

		public List<AppVersionDownload> LstUpdateDownloads { get; set; }

		public AppRegistration()
		{
			RegisteredDateTime = DateTime.UtcNow;
		}
	}
}
